publishDir = "docs"

# Site settings
baseurl = ""
languageCode = "en-us"
title = "RebelConf 2017"
theme = "hugo-freelancer-theme-master"

[params]
    name = "Rebel Conf"
    # Custom assets
	custom_css = ["css/rebelconf.css"]
	custom_js  = []

    [params.navigation]
        brand = "Rebel Conf"
        logo = "rebelconf-logo-blue.png"
        ticketsUrl = "https://www.eventbrite.ie/e/rebelcon-tickets-33809048775"

    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "rebelconf-logo.png"
        tagline = "Cork's Software Engineering Conference"
        subtitle = "Agile | Engineering best practices | Design"

    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Speakers"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"

    [params.about]
        title = "About"
        left = "Cork is currently enjoying a huge expansion in its software industry. With global giants and local SME’s building world leading software products and blazing a trail in the tech sector, it seems unusual that there hasn’t been a dedicated software development conference so far. Well that’s all about to change as local tech giants Newsweaver and DesignWizard join forces with Skillnet Cork to bring RebelCon Leeside."
        right = "RebelCon is a not for profit technology conference run by the developer community for the developer community. It’s happening on 16th June 2017 at the newly opened Republic of Work located on the South Mall.<br/>It features a line up of national and international speakers with a wealth of software industry experience. Talks on the day will span the latest technology, cultural and development practices in the software industry."


    [params.schedule]
        title = "Schedule"
        left = "Duis dui justo, consequat a nibh nec, rhoncus semper tellus. Pellentesque id quam nec urna sodales imperdiet sed vitae turpis. Pellentesque auctor cursus purus eget semper. Fusce laoreet fermentum purus in accumsan. Fusce varius, magna vel finibus laoreet, ex nulla sollicitudin lorem, eget rhoncus leo dolor gravida lectus. Donec in nisi vel nisi efficitur ornare. Curabitur et interdum nisl."
        right = "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam bibendum, elit quis interdum vestibulum, turpis nisl porttitor magna, sollicitudin sodales libero dui ac lectus. Fusce sed commodo massa. Pellentesque aliquam cursus mauris in tempor. Praesent porta arcu at nisl tempus, ut elementum dui aliquam. Fusce venenatis luctus nisi ac varius. Aliquam placerat id nisl eget fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;"

	[params.location]
        title = "Location"
        place = "Republic of Work"
        address = "12 South Mall, Cork, Ireland"

    [params.sponsors]
        title = "Sponsors"

